import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {
  const [query, setQuery] = useState('steve');

  useEffect(() => {
    const fetchHackerNews = async (search) => {
      const res = await fetch(`api/yt-search/${search}`);
      const data = await res.json();
      const articles = data.hits;

      if (articles) {
        console.log(articles[0]);
      }
    };

    fetchHackerNews(query)
  }, [query])

  const handleSubmit = e => {
    e.preventDefault();

    const search = e.target['youtube-search'].value;
    if (search) {
      setQuery(search);
      e.target['youtube-search'].value = "";
    }
  };

  return (
    <>
      <Head>
        <title>YoutubeFocus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <div>
            <h1>YoutubeFocus</h1>
            <form
              onSubmit={handleSubmit}
              autoFocus
              autoComplete="off"
            >
              <label htmlFor="youtube-search">Search</label>
              <input type="text" name="youtube-search" id="youtube-search" />
            </form>
          </div>
        </div>
      </main>
    </>
  )
}

// Response from api/yt-search/[query] is an array of items...
// Each YouTube video item JSON looks like:

/* 
   {
    "kind": "youtube#searchResult",
    "etag": "Ob3Mbk-21J5VzmsfxUbDfzCR2OE",
    "id": {
      "kind": "youtube#video",
      "videoId": "9iqwYOgnzxE"
    },
    "snippet": {
      "publishedAt": "2020-08-21T04:00:01Z",
      "channelId": "UCFkoPRmuxqr37jvGmmpzhzQ",
      "title": "Maluma - Madrid (Audio) ft. Myke Towers",
      "description": "Maluma feat. Myke Towers – Madrid (Cover Audio) Top Hits: https://smarturl.it/malumatophits My Channel: ...",
      "thumbnails": {
        "default": {
          "url": "https://i.ytimg.com/vi/9iqwYOgnzxE/default.jpg",
          "width": 120,
          "height": 90
        },
        "medium": {
          "url": "https://i.ytimg.com/vi/9iqwYOgnzxE/mqdefault.jpg",
          "width": 320,
          "height": 180
        },
        "high": {
          "url": "https://i.ytimg.com/vi/9iqwYOgnzxE/hqdefault.jpg",
          "width": 480,
          "height": 360
        }
      },
      "channelTitle": "MalumaVEVO",
      "liveBroadcastContent": "none",
      "publishTime": "2020-08-21T04:00:01Z"
    }
  },
*/

